name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.4.0-rc2

      - name: Show Forge version
        run: |
          cd contracts
          forge --version

      - name: Run Forge fmt
        id: fmt
        run: |
          cd contracts
          forge fmt --check

      - name: Run Forge build
        id: build
        run: |
          cd contracts
          forge build --sizes

      - name: Run Forge tests
        id: test
        run: |
          cd contracts
          forge test -vvv
